version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout
      - run:
          name: Build and Test
          command: ./fake.sh run build.fsx
